package com.example.kogebog.contents

object IndholdHovedret {

    var title = arrayOf(
        "Lasagne",
        "Spaghetti Bolognese",
        "Stegt flæsk med persillesovs",
        "Hjemmelavet burgere",
        "Fyldt mørbrad med cremet grønkål og hasselnødder"
    )
    var ingredients = arrayOf(
        "50 g bacon \n 2 løg, finthakket \n 2 fed hvidløg, finthakket \n 3 stænger frisk timian, eller 2 tsk tørret \n 500 g hakket oksekød \n 1 dl rødvin \n 100 g soltørrede tomater, finthakket \n 2 spsk rød balsamico \n 2 dåser hakkede tomater \n 2 spsk olivenolie \n salt \n sort peber, friskkværnet",
        "2 løg, finthakket \n 4 fed hvidløg, finthakket \n 400 g hakket oksekød \n 2 tsk oregano, tørret\n 1 tsk timian, tørret \n 4 gulerod, groftrevet \n 5 stængler bladselleri, groftrevet \n 1 squash, groftrevet \n 1 dl tomatpuré \n 2 dåser hakkede tomater \n 1 dl rødvin, eller grøntsagsboullion \n 2 spsk olivenolie \n salt \n sort peber, friskkværnet",
        "800 g flæsk, i skiver \n 2 spsk smør \n 2 spsk hvedemel \n 5 dl mælk \n 0,50 øko citron, saft og skal herfra \n 2 håndfulde persille, finthakket \n salt \n sort peber, friskkværnet",
        "3 dl vand \n 25 g gær \n 1 tsk salt \n 2 spsk olivenolie \n 3 spsk hørfrø \n 150 g oliven uden sten, grofthakket \n 100 g fuldkornshvedemel \n 400 g hvedemel \n 1 tsk olivenolie, til at pensle med \n 1 tsk flagesalt \n 600 g hakket oksekød \n 3 spsk soltørrede tomater, finthakket \n 1 tsk worcestershire sauce \n 1 æg \n 0,50 tsk røget paprika \n 1 fed hvidløg, presset \n 1 skive bacon, sprødristet og finthakket \n 1 tsk salt \n sort peber, friskkværnet",
        "700 g svinemørbrad \n 40 g hasselnødder, finthakket \n 50 g grønkål, finthakket \n 1 fed hvidløg, presset \n 1 spsk smør \n 150 g flødeost, naturel \n 2 spsk tranebær, tørrede og finthakkede \n 140 g parmaskinke \n salt \n sort peber"
    )
    var procedure = arrayOf(
        "Sauter løg og hvidløg i olivenolie, til de er gennemsigtige. Tilsæt kødet og brun det ved høj varme. Skru ned for varmen og tilsæt resten af ingredienserne. Lad saucen simrekoge under låg i 2-6 timer – jo længere jo bedre. Smag på saucen løbende og smag til med fx. grøntsagsbouillon, flere krydderier, tomatpuré, flåede tomater efter smag – og endelig også salt og peber. Smelt smørret i en gryde, kom mel i og pisk, til det har samlet sig til en bolle. Pisk mælken langsomt i lidt ad gangen, til konsistensen er som en sauce. Kom ost i og pisk, til den er smeltet. Smag til med revet muskatnød, salt og peber. Kom et lag mornaysauce i et smurt ovnfast fad. Kom derefter skiftevis lasagnesauce og -plader i fadet og slut af med sauce. Top til sidst med et lag mornaysauce. Kom fadet i en forvarmet ovn ved 175 grader varmluft og bag lasagnen i ca. 20-25 minutter, til lasagnepladerne er møre med lidt bid.",
        "Steg bacon i olivenolie i en tykbundet gryde ved middelhøj varme. Tag baconen op og lad den dryppe af på et stykke køkkenrulle. Kom løg, hvidløg og timian i gryden med baconfedt og steg det under omrøring, til løgene er bløde og klare. Tilsæt kødet og brun det, hæld rødvinen ved og lad det koge lidt ind. Tilsæt soltørrede tomater, balsamico og hakkede tomater. Skær den ristede bacon i små tern og kom den tilbage i gryden. Læg låg på og lad det simre i en times tid ved lav varme. Hold øje med, at det ikke koger tørt, tilsæt lidt ekstra grøntsagsboullion eller rødvin. Hvis saucen er for våd, så tag låget af og kog lidt op, mens spaghettien gøres klar. Kog spaghetti efter anvisning på pakken. Server pastaen i dybe tallerkener med bolognese, et stænk olivenolie og masser af friskrevet parmesanost.",
        "Drys lidt salt over flæsket og læg det på en rist over en bradepande beklædt med bagepapir. Steg flæskeskiverne i en forvarmet ovn ved 175 grader i 30-40 minutter og vend dem et par gange undervejs. Kom  kartoflerne i en gryde med rigeligt letsaltet koldt vand, kog op og kog derefter i cirka 20 minutter alt efter størrelsen af kartoflerne. Tjek om de er klar og møre og hæld derefter vandet fra. De kan holde sig lune i gryden med låg på (uden vand) til flæsk og saucen er klar. Smelt smør i en gryde ved lav varme, pisk mel i, til det er en jævn masse, og pisk derefter mælk i lidt ad gangen. Kog persillesaucen i ca. 5 minutter ved middelvarme, mens den piskes igennem, og smag den til med citronsaft og -skal, persille samt salt og peber.",
        "Rør vand og gær sammen i en skål, tilsæt olivenolie, hørfrø, oliven, salt og fuldkornsmel. Rør hvedemel lidt af gangen til dejen kan æltes på bordpladen. Dejen skal ikke være hård, men blød, smidig og må gerne klistre en smule. Lad den hæve i skålen i 30 minutter. Slå dejen sammen, form 10 boller og lad dem hæve på en bageplade med bagepapir i 1 1/2 time. Pensl med lidt olivenolie og drys med flagesalt. Sæt bollerne i en forvarmet ovn ved 250 grader varmluft, skrue straks ned til 200 grader varmluft og bag bollerne i 15-18 minutter. Lad dem køle af på en rist. Overskydende boller kan fryses ned. Kom alt fyldet til bøfferne i en skål, inkl soltørrede tomater, finthakket bacon, æg osv. Det hele æltes godt sammen i en skål. Form 4 bøffer og pres dem flade. Steg bøfferne 4-5 min på hver side ved middelvarme i smør. Lige inden de er færdige kan lægges en osteskive på og sprød bacon. Burgeren samles med ost, bacon, salat, tomat, agurk, løgringe, mayonnaise, og krydderurter.",
        "Varm ovnen op til 150 grader og rist hasselnødderne i ovnen i 10 minutter, til hinden revner og løsner sig. Tag hasselnødderne ud af ovnen og kom dem i et viskestykke. Gnid den brune hinde af i viskestykket. Hak hasselnødderne groft. Kom grønkål og hvidløg på en pande med smør og sauter det ved middelvarme, til grønkålen falder lidt sammen. Smag til med salt og peber og rør flødeost, hasselnødder og tranebær i. Afpuds svinemørbraden for sener og skær en dyb lomme i mørbraden, så der er god plads til fyldet. Krydr mørbraden med salt og peber og kom fyldet i lommen. Luk mørbraden og pak den ind i parmaskinke. Læg mørbraden i et smurt ovnfast fad og bag den i en forvarmet ovn ved 175 grader varmluft i cirka 35 minutter."
    )

}